/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ReportDumpRouteImport } from './routes/report-dump'
import { Route as ReportOffenderRouteImport } from './routes/report-offender'
import { Route as SocialCreditRouteImport } from './routes/social-credit'
import { Route as TrackRouteImport } from './routes/track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDumpRoute = ReportDumpRouteImport.update({
  id: '/report-dump',
  path: '/report-dump',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportOffenderRoute = ReportOffenderRouteImport.update({
  id: '/report-offender',
  path: '/report-offender',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialCreditRoute = SocialCreditRouteImport.update({
  id: '/social-credit',
  path: '/social-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/report-dump': typeof ReportDumpRoute
  '/report-offender': typeof ReportOffenderRoute
  '/social-credit': typeof SocialCreditRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/report-dump': typeof ReportDumpRoute
  '/report-offender': typeof ReportOffenderRoute
  '/social-credit': typeof SocialCreditRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/report-dump': typeof ReportDumpRoute
  '/report-offender': typeof ReportOffenderRoute
  '/social-credit': typeof SocialCreditRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/report-dump'
    | '/report-offender'
    | '/social-credit'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/report-dump'
    | '/report-offender'
    | '/social-credit'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/report-dump'
    | '/report-offender'
    | '/social-credit'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ReportDumpRoute: typeof ReportDumpRoute
  ReportOffenderRoute: typeof ReportOffenderRoute
  SocialCreditRoute: typeof SocialCreditRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-dump': {
      id: '/report-dump'
      path: '/report-dump'
      fullPath: '/report-dump'
      preLoaderRoute: typeof ReportDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-offender': {
      id: '/report-offender'
      path: '/report-offender'
      fullPath: '/report-offender'
      preLoaderRoute: typeof ReportOffenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-credit': {
      id: '/social-credit'
      path: '/social-credit'
      fullPath: '/social-credit'
      preLoaderRoute: typeof SocialCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ReportDumpRoute: ReportDumpRoute,
  ReportOffenderRoute: ReportOffenderRoute,
  SocialCreditRoute: SocialCreditRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
